// models/User.js
const UserSchema = new mongoose.Schema({
    uuid: { type: String, required: true, unique: true },
    name: { type: String, required: true },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    highest_education: { type: String },
    bio: { type: String },
    gender: { type: Boolean },
    dob: { type: Date },
    address: { type: String },
    Ug_Institute_Name: { type: String },
    Ug_Institute_Location: { type: String },
    Pg_Institute_Name: { type: String },
    Pg_Institute_Location: { type: String },
    has_done_phd: { type: Boolean },
    user_type: { type: Boolean },
    longevity: { type: String },
    no_of_total_jobs: { type: Number },
    user_from_jk: { type: String },
    user_state: { type: String },
    training: { type: Number },
    workshops: { type: Number },
    books: { type: Number },
    patents: { type: Number },
    papers: { type: Number },
    achievements: { type: Number },
    openness_score: { type: Number },
    conscientiousness_score: { type: Number },
    extraversion_score: { type: Number },
    agreeableness_score: { type: Number },
    neuroticism_score: { type: Number },
    resume_file: { type: String },
    fitment_score: { type: Number },
    is_active: { type: Boolean, default: true },
    updated_at: { type: Date, default: Date.now },
    created_at: { type: Date, default: Date.now }
  });
  
  module.exports = mongoose.model('User', UserSchema);